version: "3.8"
volumes:
  db_data:
  pgadmin_data:
  mongo_data:
  redis_data:

services:
  postgres-db:
    container_name: placio-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "918273645dozie"
      POSTGRES_USER : "dozie"
      POSTGRES_DB: "placio"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: placio-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "chidosiky2015@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "918273645dozie"
      PGADMIN_LISTEN_PORT: "5050"
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db

  mongo-db:
    container_name: placio-mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dozie"
      MONGO_INITDB_ROOT_PASSWORD: "918273645dozie"

    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

#  mongo-express:
#    container_name: placio-mongo-express
#    image: mongo-express
#    restart: always
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: "dozie"
#      ME_CONFIG_MONGODB_ADMINPASSWORD: "918273645dozie"
#      ME_CONFIG_BASICAUTH_USERNAME: "dozie"
#      ME_CONFIG_BASICAUTH_PASSWORD: "918273645dozie"
#      ME_CONFIG_MONGODB_PORT: "27017"
#      ME_CONFIG_MONGODB_SERVER: "mongo-db"
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mongo-db
#
  placio-redis:
    container_name: placio-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  redis-commander:
#    container_name: placio-redis-commander
#    image: rediscommander/redis-commander:latest
#    restart: always
#    ports:
#      - "8086:8086"
#    depends_on:
#      - placio-redis
#    environment:
#      REDIS_HOSTS: placio-redis
#      REDIS_PORT: 6379
#      REDIS_URL: placio-redis://placio-redis:6379
#      REDIS_HOST_DOCKER: host.docker.internal
#      PORT: 8086
  kafka:
    container_name: placio-kafka
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "placio:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    container_name: placio-zookeeper
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

#  kafka-ui:
#    container_name: placio-kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    restart: always
#    ports:
#      - "8083:8083"
#    depends_on:
#      - kafka

  app:
    container_name: placio-app
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - postgres-db
      - mongo-db
#      - redis
#      - kafka
#      - zookeeper
#      - kafka-ui
#      - pgadmin
#      - mongo-express
#      - redis-commander
    volumes:
      - ./:/app
      - ./cmd/app:/app/cmd/app
      - ./pkg:/app/pkg
      - ./config:/app/config

    environment:
      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db:5432/placio?sslmode=disable"

  users:
    container_name: placio-users
    build:
      context: .
      dockerfile: ./cmd/users/Dockerfile
    restart: always
    ports:
      - "7075:7075"
    depends_on:
      - postgres-db
      - mongo-db
##      - redis
#      - kafka
##      - zookeeper
#      - kafka-ui
#      - pgadmin
#      - mongo-express
##      - redis-commander
    environment:
      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db:5432/placio?sslmode=disable"
    volumes:
      - ./:/app
      - ./cmd/users:/app/cmd/users
      - ./pkg:/app/pkg
      - ./config:/app/config

  auth:
    container_name: placio-auth
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    restart: always
    ports:
      - "7076:7076"
    depends_on:
      - postgres-db
      - mongo-db
#      - redis
#      - kafka
#      - zookeeper
#      - kafka-ui
#      - pgadmin
#      - mongo-express
#      - redis-commander
    volumes:
      - ./:/app
      - ./cmd/auth:/app/cmd/auth
      - ./pkg:/app/pkg
      - ./config:/app/config
    environment:
      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db:5432/placio?sslmode=disable"

  media:
    container_name: placio-media
    build:
      context: .
      dockerfile: ./cmd/media/Dockerfile
    restart: always
    ports:
      - "7074:7074"
    depends_on:
      - postgres-db
      - mongo-db
#      - redis
#      - kafka
#      - zookeeper
#      - kafka-ui
#      - pgadmin
#      - mongo-express
#      - redis-commander
    volumes:
      - ./:/app
      - ./cmd/media:/app/cmd/media
      - ./pkg:/app/pkg
      - ./config:/app/config
    environment:
      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db:5432/placio?sslmode=disable"
#
  events:
    container_name: placio-events
    build:
      context: .
      dockerfile: ./cmd/events/Dockerfile
    restart: always
    ports:
      - "7073:7073"
    depends_on:
      - postgres-db
      - mongo-db
#      - redis
#      - kafka
#      - zookeeper
#      - kafka-ui
#      - pgadmin
#      - mongo-express
#      - redis-commander
    volumes:
      - ./:/app
      - ./cmd/events:/app/cmd/events
      - ./pkg:/app/pkg
      - ./config:/app/config
    environment:
      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db:5432/placio?sslmode=disable"

  chats:
    container_name: placio-chats
    build:
      context: .
      dockerfile: ./cmd/chats/Dockerfile
    restart: always
    ports:
      - "7077:7077"
    depends_on:
      - postgres-db
      - mongo-db
#      - redis
#      - kafka
#      - zookeeper
#      - kafka-ui
#      - pgadmin
#      - mongo-express
#      - redis-commander
    volumes:
      - ./:/app
      - ./cmd/chats:/app/cmd/chats
      - ./pkg:/app/pkg
      - ./config:/app/config

    environment:
      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db:5432/placio?sslmode=disable"
#
  business:
    container_name: placio-business
    build:
      context: .
      dockerfile: ./cmd/business/Dockerfile
    restart: always
    ports:
      - "7071:7071"
    depends_on:
      - postgres-db
      - mongo-db
#      - redis
#      - kafka
#      - zookeeper
#      - kafka-ui
#      - pgadmin
#      - mongo-express
#      - redis-commander
    volumes:
      - ./:/app
      - ./cmd/business:/app/cmd/business
      - ./pkg:/app/pkg
      - ./config:/app/config

    environment:
      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db:5432/placio?sslmode=disable"
