version: "3.8"
volumes:
  db_data:
  pgadmin_data:
  mongo_data:
  redis_data:

services:
  postgres-db:
    container_name: placio-postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: placio-pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.envs/.local
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-db

  placio-redis:
    container_name: placio-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  docs:
    container_name: placio-docs
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    restart: always
    ports:
      - "6060:6060"
    volumes:
      # - ./:/app
      - ./docs:/app/docs
  # kafka:
  #   container_name: placio-kafka
  #   image: wurstmeister/kafka:2.12-2.5.0
  #   restart: always
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: localhost
  #     KAFKA_ADVERTISED_PORT: 9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "placio:1:1"
  #   depends_on:
  #     - zookeeper

  # zookeeper:
  #   container_name: placio-zookeeper
  #   image: wurstmeister/zookeeper:latest
  #   restart: always
  #   ports:
  #     - "2181:2181"

#  kafka-ui:
#    container_name: placio-kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    restart: always
#    ports:
#      - "8083:8083"
#    depends_on:
#      - kafka

  app:
    container_name: placio-app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - postgres-db
    volumes:
      - ./:/app
      - ./cmd/app:/app/cmd/app
      - ./config:/app/config
    env_file:
      - ./.envs/.local
      


