version: "3.8"
volumes:
  db_data:
  pgadmin_data:
  mongo_data:
  redis_data:
  es_data:
  prometheus_data:
  grafana_data:

services:
  #  unleash:
  #    image: unleashorg/unleash-server:latest
  #    ports:
  #      - "4242:4242"
  #    environment:
  #      # This points Unleash to its backing database (defined in the `db` section below)
  #      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db/postgres"
  #      DATABASE_SSL: "false"
  #      LOG_LEVEL: "warn"
  #      # Proxy clients must use one of these keys to connect to the
  #      # Proxy. To add more keys, separate them with a comma (`key1,key2`).
  #      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
  #      # Initialize Unleash with a default set of client API tokens. To
  #      # initialize Unleash with multiple tokens, separate them with a
  #      # comma (`token1,token2`).
  #      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
  ##    depends_on:
  ##      db:
  ##        condition: service_healthy
  #    command: [ "node", "index.js" ]
  ##    healthcheck:
  ##      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
  ##      interval: 1s
  ##      timeout: 1m
  ##      retries: 5
  app:
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    volumes:
      - ./:/app
      - ./cmd/app:/app/cmd/app
      - ./config:/app/config
    env_file:
      - ./.envs/.local

  feeds:
    build:
      context: .
      dockerfile: ./placid-feed/Dockerfile
    restart: always
    ports:
      - "7071:7071"
    volumes:
      - ./:/app
      - ./placid-feed:/app/placid-feed
      - ./config:/app/config
    env_file:
      - ./.envs/.local



