version: "3.8"

services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "918273645dozie"
      POSTGRES_USER : "dozie"
      POSTGRES_DB: "placio"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "chidosiky2015@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "918273645dozie"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  # user:
  #   container_name: placio-user
  #   build:
  #     context: .
  #     dockerfile: ./cmd/user/Dockerfile
  #   restart: always
  #   networks:
  #     - placio
  #   depends_on:
  #     - db

  # auth:
  #   container_name: placio-auth
  #   build:
  #     context: .
  #     dockerfile: ./cmd/auth/Dockerfile
  #   restart: always
  #   networks:
  #     - placio
  #   depends_on:
  #     - db

  # migration:
  #   container_name: placio-migration
  #   build:
  #     context: .
  #     dockerfile: ./cmd/migrate/Dockerfile
  #   restart: always
  #   networks:
  #     - placio
  #   depends_on:
  #     - db

volumes:
  db_data:
  pgadmin_data:

networks:
  default:
    external:
      name: nginx-proxy
  placio:
    name: placio
