version: "3.8"
volumes:
  db_data:
  pgadmin_data:
  mongo_data:
  redis_data:
  es_data:
  prometheus_data:
  grafana_data:

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: dozie
      POSTGRES_PASSWORD: 918273645dozie
      POSTGRES_DB: placio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U dozie" ]
#      interval: 30s
#      timeout: 30s
#      retries: 3

  #  unleash:
  #    image: unleashorg/unleash-server:latest
  #    ports:
  #      - "4242:4242"
  #    environment:
  #      # This points Unleash to its backing database (defined in the `db` section below)
  #      DATABASE_URL: "postgres://dozie:918273645dozie@postgres-db/postgres"
  #      DATABASE_SSL: "false"
  #      LOG_LEVEL: "warn"
  #      # Proxy clients must use one of these keys to connect to the
  #      # Proxy. To add more keys, separate them with a comma (`key1,key2`).
  #      INIT_FRONTEND_API_TOKENS: "default:development.unleash-insecure-frontend-api-token"
  #      # Initialize Unleash with a default set of client API tokens. To
  #      # initialize Unleash with multiple tokens, separate them with a
  #      # comma (`token1,token2`).
  #      INIT_CLIENT_API_TOKENS: "default:development.unleash-insecure-api-token"
  ##    depends_on:
  ##      db:
  ##        condition: service_healthy
  #    command: [ "node", "index.js" ]
  ##    healthcheck:
  ##      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
  ##      interval: 1s
  ##      timeout: 1m
  ##      retries: 5
  app:
    #    container_name: placio-app
    # platform: linux/x86_64
    build:
      context: .
#      dockerfile: ./cmd/app/Dockerfile
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./cmd/app:/app/cmd/app
      - ./config:/app/config
    env_file:
      - ./.envs/.local

#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prometheus_data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/local.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
#    ports:
#      - 9090:9090
#
#  grafana:
#    image: grafana/grafana:latest
#    volumes:
#      - grafana_data:/var/lib/grafana
#    ports:
#      - 3000:3000

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.47.0
#    container_name: cadvisor
#    ports:
#      - "8080:8080"
#    network_mode: host
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro
#    devices:
#      - /dev/kmsg
#    privileged: true
#    restart: unless-stopped

#  node_exporter:
#    image: quay.io/prometheus/node-exporter:v1.5.0
#    container_name: node_exporter
#    command: "--path.rootfs=/host"
#    pid: host
#    restart: unless-stopped
#    volumes:
#      - /:/host:ro,rslave


