version: "3.8"

services:
  placio-backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
      - "50051:50051"
    volumes:
      # - ./:/app
      - ./app:/app/app
      - ./pkg:/app/pkg
      - ./config:/app/config
      - ./app/domains/media/serviceAccount.json:/app/serviceAccount.json
    env_file:
      - .envs/.local

  ws:
    build:
      context: .
      dockerfile: ./realtime_server/Dockerfile
    restart: always
    depends_on:
      - placio-backend
    ports:
      - "7080:7080"
    volumes:
      # - ./:/app
      - ./realtime_server:/work/realtime_server
      - ./pkg:/work/pkg
      # - ./config:/app/config
    env_file:
      - .envs/.local
