version: "3.8"
volumes:
  db_data:
  pgadmin_data:
  mongo_data:
  redis_data:

services:
  docs:
    container_name: placio-docs
    build:
      context: .
      dockerfile: ./docs/Dockerfile
    restart: always
    ports:
      - "6060:6060"
    volumes:
      # - ./:/app
      - ./docs:/app/docs

  #  kafka-ui:
  #    container_name: placio-kafka-ui
  #    image: provectuslabs/kafka-ui:latest
  #    restart: always
  #    ports:
  #      - "8083:8083"
  #    depends_on:
  #      - kafka

  app:
    #    container_name: placio-app
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    #    depends_on:
    #      - postgres-db
    volumes:
      - ./:/app
      - ./cmd/app:/app/cmd/app
      - ./config:/app/config
    env_file:
      - ./.envs/.local

  server:
    # container_name: server
    build:
      context: ./placio-auth
      dockerfile: Dockerfile.dev
    ports:
      - "3004:3004"
    volumes:
      - ./placio-auth:/app
      - /app/node_modules
    restart: "unless-stopped"
