version: "3.8"
volumes:
  db_data:
  pgadmin_data:
  mongo_data:
  redis_data:

services:
  # docs:
  #   container_name: placio-docs
  #   build:
  #     context: .
  #     dockerfile: ./docs/Dockerfile
  #   restart: always
  #   ports:
  #     - "6060:6060"
  #   volumes:
  #     # - ./:/app
  #     - ./docs:/app/docs

  #  kafka-ui:
  #    container_name: placio-kafka-ui
  #    image: provectuslabs/kafka-ui:latest
  #    restart: always
  #    ports:
  #      - "8083:8083"
  #    depends_on:
  #      - kafka

  newrelic-infra:
    image: newrelic/infrastructure:latest
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - NRIA_LICENSE_KEY=eu01xx48a40b16fb787caed094a43278c919NRAL
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: dozie
      POSTGRES_PASSWORD: 918273645dozie
      POSTGRES_DB: placio
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    #    container_name: placio-app
    # platform: linux/x86_64
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    #    depends_on:
    #      - postgres-db
    volumes:
      - ./:/app
      - ./cmd/app:/app/cmd/app
      - ./config:/app/config
    env_file:
      - ./.envs/.local
