version: "3.8"

services:
  postgres-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "918273645dozie"
      POSTGRES_USER : "dozie"
      POSTGRES_DB: "placio"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "chidosiky2015@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "918273645dozie"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "dozie"
      MONGO_INITDB_ROOT_PASSWORD: "918273645dozie"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "dozie"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "918273645dozie"
    ports:
      - "8081:8081"
    depends_on:
      - mongo-db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8082:8081"
    depends_on:
      - redis

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "placio:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - kafka

  app:
    build: 
      context: .
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - postgres-db
      - mongo-db
      - redis
      - kafka
      - zookeeper
      - kafka-ui
      - pgadmin
      - mongo-express
      - redis-commander
  