version: '3.4'
services:
  test_africa_insight:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        DB_CONNECTION: "postgresql://postgres:mysecretpassword@db:5432/postgres"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && make test"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/africa_insight
    links:
      - "db:db"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  africa_insight:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        DB_CONNECTION: "postgresql://postgres:mysecretpassword@db:5432/postgres"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && python ./africa_insight/main.py"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/africa_insight
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/version"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "db:db"
    depends_on:
      - db