version: "3.4"
services:
  africa_insight:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        DB_CONNECTION: "postgresql://postgres:918273645dozie@db:5432/postgres"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && python ./africa_insight/main.py"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/africa_insight
    ports:
      - "8383:8383"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8383/api/v1/version"]
      interval: 1m30s
      timeout: 10s
      retries: 3
