api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt
  metrics:
    address: :8082

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: chidosiky2015@gmail.com
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web

metrics:
  prometheus:
    entryPoint: "metrics"
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
