# Dynamic configuration
http:
  middlewares:
    corsHeaders:
      headers:
        accessControlAllowOrigin: "*"
        accessControlAllowMethods: [ "GET","OPTIONS","PUT","POST","DELETE","PATCH" ]
        accessControlAllowCredentials: true
        accessControlAllowHeaders: [ "Accept", "Accept-Language", "Content-Language", "Content-Type", "DPR", "Origin", "Authorization", "X-Requested-With", "X-CSRF-Token", "X-Auth-Token", "X-Forwarded-For", "X-Real-IP", "X-Forwarded-Proto", "X-Forwarded-Host", "X-Forwarded-Port", "X-Forwarded-Server", "X-Forwarded-By", "X-Request-ID", "X-Correlation-ID" ]
        accessControlExposeHeaders: [ "Content-Length" ]
        accessControlMaxAge: 100
        addVaryHeader: true
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    user-auth:
      basicAuth:
        users:
          - 'admin:918273645dozie'

tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12
