type: object
properties:
  BlockedUsers:
    type: array
    description: BlockedUsers holds the value of the "BlockedUsers" field.
    items:
      type: string
  MutedUsers:
    type: array
    description: MutedUsers holds the value of the "MutedUsers" field.
    items:
      type: string
  TwoFactorAuthentication:
    type: boolean
    description: >-
      TwoFactorAuthentication holds the value of the "TwoFactorAuthentication"
      field.
  edges:
    type: object
    description: >-
      Edges holds the relations/edges for other nodes in the graph.

      The values are being populated by the AccountSettingsQuery when
      eager-loading is set.
    allOf:
      - $ref: '#/definitions/placio-app_ent.AccountSettingsEdges'
  id:
    type: string
    description: ID of the ent.
