name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy-stag:
    runs-on: self-hosted
    env:
      DOMAIN: stag.palnight.com
      TRAEFIK_TAG: stag.palnight.com
      STACK_NAME: stag-api-palnight-com
      TAG: stag
    steps:
      - name: remove old stack
        run: echo ${{ secrets.VPS_PASSWORD }} | 
          sudo -S rm -rf /home/dozie/nightout-server/_work/nightout-server/nightout-server/backend
      - name: remove old stack
        run: echo ${{ secrets.VPS_PASSWORD }} | 
          sudo -S rm -rf /home/dozie/nightout-server/_work/nightout-server/nightout-server/portainer-data
      - name: remove old stack
        run: echo ${{ secrets.VPS_PASSWORD }} | 
          sudo -S rm -rf /home/dozie/nightout-server/_work/nightout-server/nightout-server/traefik-data
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add Permission To acme.json
        run: |
          chmod 600 ./traefik-data/acme.json
      - name: Start Docker Container
        run: echo "Starting containers" |
          echo ${{ secrets.VPS_PASSWORD }} |
          sudo -S docker-compose -f docker-compose.deploy.yml up --build -d

