name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/deploy
      - master
  pull_request:
    branches:
      - feat/deploy
      - master

jobs:
  deploy-stag:
    runs-on: self-hosted
    env:
      TAG: stag

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Remove old application stack
        run: |
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S rm -rf /home/placio/placio-api/_work/placio-api/placio-api/backend
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S rm -rf /home/placio/placio-api/_work/placio-api/placio-api/portainer
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S rm -rf /home/placio/placio-api/_work/placio-api/placio-api/traefik

      - name: Build and Start Docker Containers
        run: |
          echo "Starting containers"
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker-compose -f docker-compose.stag.yml up --build -d
