name: CI/CD Pipeline

on:
  push:
    branches:
      - feat/deploy
      - master
  pull_request:
    branches:
      - feat/deploy
      - master

jobs:
  deploy-stag:
    runs-on: self-hosted
    env:
      TAG: stag

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#        with:
#          driver: docker-container
#          buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
#          install: false
#          use: true
#          cleanup: true
#
#      - name: Cache Docker layers
#        uses: actions/cache@v2
#        with:
#          path: /tmp/.buildx-cache
#          key: ${{ runner.os }}-buildx-${{ github.sha }}
#          restore-keys: |
#            ${{ runner.os }}-buildx-

      - name: Remove old application stack
        run: |
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S rm -rf /home/placio/placio-api/_work/placio-api/placio-api/backend
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S rm -rf /home/placio/placio-api/_work/placio-api/placio-api/portainer
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S rm -rf /home/placio/placio-api/_work/placio-api/placio-api/traefik

      - name: Build and Start Docker Containers
        run: |
          echo "Starting containers"
          echo ${{ secrets.VPS_PASSWORD }} | sudo -S docker-compose -f docker-compose.stag.yml up --build -d --force-recreate --remove-orphans
