name: Run Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker Compose
        run: docker-compose up --build -d

      - name: Run tests
        run: |
          chmod +x wait-for-it.sh
          chmod +x wait-for-server.sh
          chmod +x test.sh
          ./test.sh
