name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install dependencies
        run: go mod download

      - name: Build Docker Compose
        run: docker-compose up --build -d

      - name: Run tests
        run: |
          curl -sSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh localhost:7070 --timeout=15 --strict -- make test

      - name: Shutdown Docker Compose
        run: docker-compose down
